### ISSUE TITLE
Thank you for making Pstros real! I've got a question for you

### ISSUE THREAD

**Issue by MadRatSRP** [ole00/pstros-nds#1]
Do u have an account in Telegram or Facebook? I would like to talk with you about Jade, Pstros and Pstros nds

**Comment by ole00** [comment]
I don't do Telegram nor Facebook. Feel free to ask questions related to the project here.

**Comment by MadRatSRP** [comment]
Okay, then please tell me how can I contact you? Maybe through the email?
