### ISSUE TITLE
Could you please tell me how can i contact you ? 

### ISSUE THREAD

**Issue by MadRatSRP** [ole00/pstros-nds#2]
I want to recompile pstros nds and add a new J2ME apis from J2ME Loader app, but i need your help about last version of the DevKitPro you used for the development. Because with these versions that i could find i couldnt build it

**Comment by MadRatSRP** [comment]
I won't spam again but please write your email address or other way to communicate with you. Thanks

**Comment by ole00** [comment]
That's the version of dvkitpro I used back then (installed.ini)
```
[mirror]
url=

[msys]
Version=1.0.11-RC2

[devkitARM]
Version=25

[devkitPPC]
Version=16a

[devkitPSP]
Version=11

[libgba]
Version=20090222

[libnds]
Version=1.3.2

[libmirko]
Version=0.9.7

[pnotepad]
Version=2.0.8.718

[insight]
Version=6.8.50-20080425

[ndsexamples]
Version=20090221

[gbaexamples]
Version=20090222

[cubeexamples]
Version=20081206

```

My email address is in the git commits. use 'git log' to check it out. Hope it helps.
