### ISSUE TITLE
r

### ISSUE THREAD

**Issue by dananothername** [ole00/pstros-nds#3]

**Comment by ole00** [comment]
Bizhawk is written in C#. Supporting java apps in C# would not be trivial - also the whole Pstros MIDP and J2ME frontend would have to be ported over from java to C#. It is better to use existing MIDP/J2ME emulators - Retroarch seems to have 2 cores that do that. See the list here: https://docs.libretro.com/meta/core-list/

**Comment by dananothername** [comment]
well can you compile it if possible 
i want it for tas

**Comment by ole00** [comment]
Compilation of Pstros for Bizhawk is not possible without code modification - and these modifications would be worth of months of work.

**Comment by dananothername** [comment]
why i runs only on real hardware
